### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by noelhung** [apidoc/apidoc-core#103]
I found thread https://github.com/apidoc/apidoc-core/issues/60
Have tried https://www.npmjs.com/package/@forfuture/apidoc-openapi & https://www.npmjs.com/package/apidoc-swagger
However, apidoc-swagger mixed up parameters and responses & no grouping available in apidoc-openapi
Is there any suggestions to convert it to openAPI?

**Comment by ccakes** [comment]
There's also [apidoc-swagger-3](https://www.npmjs.com/package/apidoc-swagger-3) but I haven't been able to make it work either

**Comment by NicolasCARPi** [comment]
This is not planned at the moment.
