### ISSUE TITLE
Change default language checker

### ISSUE THREAD

**Issue by TanTan-TT** [apidoc/apidoc-core#113]
# Feature request

Hi, I want to use apidoc to generate api for my project, which is based on playframework ( scala's web framework). According to its spec, we should write external APIs in a file named route, which is non-file-extension file. But its grammar for comment is not java-like. It can only use one-line comment by #, such as 
`#this is comment `
So I cannot use apidoc for that, I think maybe we can change default language checker, maybe I can change to use Elixir-style comment for apidoc, such as 
```
# {
# this is comment
# }
```

Thank you

**Comment by NicolasCARPi** [comment]
I have transferred your issue into apidoc-core, as this is what contains the parser.

**Comment by TanTan-TT** [comment]
> I have transferred your issue into apidoc-core, as this is what contains the parser.

Thank you. I have a suggestion for fixing this. Maybe we can modify following code 
```
app.languages = _.defaults({}, options.languages, app.languages);
```
https://github.com/apidoc/apidoc-core/blob/master/lib/index.js#L293

to

```
app.languages = _.defaults({}, app.languages, options.languages);
```

In this case, we can override default config
