### ISSUE TITLE
Field out of order for object parameter

### ISSUE THREAD

**Issue by arsframework** [apidoc/apidoc-core#114]
The parameter fields is out of order for @apiParam and @apiSuccess.

for example:

/**
 * @api { POST } /member/register/email Register by email
 * @apiSampleRequest off
 * @apiName io.exchange.member.controller.RegisterController.emailRegister
 * @apiGroup Group5
 * @apiHeader {String} Content-Type application/json
 * @apiParam { String { ^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$ } } email The email address
 * @apiParam { String { 6..6 } } verification_code The verification code
 * @apiParam { String } [ country ] The country
 * @apiParam { String } [ timezone ] The timezone
 * @apiParam { String { ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,20}$ } } password The password
 * @apiParam { String } [ identify ] Identify
 * @apiParam { String } [ invitation_code ] Invitation code
 * @apiParam { String } [ lucky_draw_id ]
 * @apiParam { String = H5(H5) , WEB(Web) , NATIVE(Native) , UNKNOWN(Unknown) } [ client_type ] Client type
 * @apiParam { String } [ geetest_user ] Geetest user
 * @apiParam { String } [ geetest_challenge ] Geetest challenge
 * @apiParam { String } [ geetest_validate ] Geetest validate
 * @apiParam { String } [ geetest_seccode ] Geetest seccode
 * @apiSuccess { Long } id The member id
 * @apiSuccess { String } token The token of session
 * @apiSuccess { String } account account
 * @apiSuccess { String = NORMAL , VIP } type Member type
 * @apiSuccess { Object } profile The member profile
 * @apiSuccess { String } profile.avatar The avatar of member
 * @apiSuccess { Object } setting The member setting
 * @apiSuccess { String } setting.language The custom language
 * @apiSuccess { Object } setting.currency The custom currency
 * @apiSuccess { String } setting.currency.name Currency name
 * @apiSuccess { String } setting.currency.icon Currency icon
 * @apiSuccess { String } timezone timezone
 * @apiSuccess { String } country country
 * @apiSuccessExample Response
 *
 * {"id":1, "token":"", "account":"", "type":"NORMAL", "profile":{"avatar":""}, "setting":{"language":"", "currency":{"name":"", "icon":""}}, "timezone":"", "country":""}
 */

![image](https://user-images.githubusercontent.com/33923975/113533008-5e867000-95ff-11eb-9aab-b091990aea8e.png)

**Comment by NicolasCARPi** [comment]
Should be fixed in next version.
