### ISSUE TITLE
Support the runtime doc generation

### ISSUE THREAD

**Issue by alex-zhang** [apidoc/apidoc-core#117]
background:

hi, i want add some decorator in typescript for generating api document in runtime(not in build time). I think it's reasonable for us.

i found that the api-core has the parseSource API, but it's difference with the parse API.   
i just need response the `https://apidocjs.com/example/api_data.js?v=1628993287127` and the `https://apidocjs.com/example/api_project.js?v=1628993287127` which is from the parseSource just like the apidoc cli does.

is that possible? 

thanks.

**Comment by NicolasCARPi** [comment]
Can't you use createDoc from apidoc?
