### ISSUE TITLE
Add @apiQuery and @apiBody

### ISSUE THREAD

**Issue by KapuzenSohn** [apidoc/apidoc-core#24]
Hey,
me and a workmate found this project by looking for some API Documentation tools.
When we used it some ideas came up. Apidoc makes no different between an URL param, query or a body param. I know all are params but it would be nice if there is more difference between those three.

Maybe I find some time to create a pull request in a couple of days.

Keep up the nice work ;)

**Comment by rottmann** [comment]
Ok thanks!

**Comment by SWheeler17** [comment]
Reopening this issue to make a pull request.
