### ISSUE TITLE
Wrench is deprecated

### ISSUE THREAD

**Issue by gerrard00** [apidoc/apidoc-core#28]
The Wrench module has been deprecated. The recommendation from the developer of Wrench is to use fs-extra.

**Comment by rottmann** [comment]
Yes thanks, i saw it, i wait for a reply of my feature request: https://github.com/jprichardson/node-fs-extra/issues/240

(i don't want to implement the function manually, even if it is not so complex).

**Comment by gerrard00** [comment]
Thanks for the update!
