### ISSUE TITLE
Add a literal escape tag

### ISSUE THREAD

**Issue by Resonance1584** [apidoc/apidoc-core#3]
Instead of allowing special characters in some fields and not others add a literal escape so users can output : or [ in fields. See http://docs.oracle.com/javase/1.5.0/docs/tooldocs/windows/javadoc.html#%7B@literal%7D

Use case:
I want to set the fieldname of my GET parameter to aaab[ccdd] but the parser only recognises alphanumeric, slash etc. Allow me to manually escape the [ and ] characters.

**Comment by sbilodeau** [comment]
I have a similar problem. I need to add documentation for [OData](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/) query string parameters which use $ as prefix.  May be markdown backslash escapes could also be a solution: http://daringfireball.net/projects/markdown/syntax#backslash

eg: 

    GET path/to/my/api/list?$filter=...&$skip=10&$top=10&$orderby=...

    /**
     * @api {get} path/to/my/api/list List
     * ...
     * @apiParam (Query String)  {String}  [\$filter]  Selects only the Entries that satisfy the predicate expression
     * @apiParam (Query String)  {String}  [\$top]     Gets only the first N items of the set
     * ...
     */

**Comment by alessandro-aglietti** [comment]
I've fixed a similar problem in https://github.com/apidoc/apidoc-core/pull/19

If you need to replace the file to support that, on  debian, change
/usr/lib/node_modules/apidoc/node_modules/apidoc-core/lib/parsers/api_param.js
with
https://raw.githubusercontent.com/alessandro-aglietti/apidoc-core/master/lib/parsers/api_param.js

**Comment by 2naive** [comment]
I have the same problem but inside @apiExample:

```
 * @apiExample {ruby} Ruby
 * require "greensms"
 * @client = GreenSMS::GreenSMSClient.new(user: "test", pass: "test")
 * response = @client.call.send(to: '70000000000')
 * puts response["code"]
 ```
 
 -- breaks on @client.
