### ISSUE TITLE
Extend an existing parser

### ISSUE THREAD

**Issue by bpaz** [apidoc/apidoc-core#31]
Hello. I am trying to extend the @apiSuccessExample annotation to add some options like loading the response body from an external json file. I have created a new Hook that calls my custom parser function. The problem is that the original parser is not called anymore, so the original logic is not working anymore. I thought of "copy" the original code to my function but it has some dependencies on apidoc core libraries.

Any ideas?

**Comment by NicolasCARPi** [comment]
Closing because old and probably not relevant anymore.
