### ISSUE TITLE
@group Can not recognize Chinese characters

### ISSUE THREAD

**Issue by skynice** [apidoc/apidoc-core#33]
i found in [apidoc-core/blob/master/lib/workers/api_group.js] 
  
> group = group.replace(/[^\w]/g, '_');

when Chinese characters in use ，the content replace by _

**Comment by love8587** [comment]
Hello,

A few month ago, I also found the problem.
So I resolved the problem by modifying the source as shown below.

https://github.com/apidoc/apidoc-core/pull/17


I hope it would be helpful to you.

**Comment by skynice** [comment]
ok,thank you.
