### ISSUE TITLE
WARN deprecated wrench@1.5.9: wrench.js is deprecated!

### ISSUE THREAD

**Issue by avshelestov** [apidoc/apidoc-core#38]
I'm trying to install apidoc npm module, but:

> npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

**Comment by alqu** [comment]
Same here.
As it seems, the only usage of "wrench" is in lib/utils/find_files.js for the method "readdirSyncRecursive".

Someone has to replace the code as it has been done e.g. like here:
https://github.com/jsdoc3/jsdoc/commit/5ca4590a9e889442770b440d5d76f17fe80dd77f#diff-c261130191b3954c0ab20303d80533faR83

Hope to help,

Michael

**Comment by alqu** [comment]
It seems the issue can be closed. Thanks!
