### ISSUE TITLE
Remove HTML tags from generated JSON

### ISSUE THREAD

**Issue by tylucaskelley** [apidoc/apidoc-core#6]
I noticed that in the generated JSON output, there are p tags in sections like description and type, etc. Example:

```json
{
    "type": "get",
    "url": "/assembly/definition/:did/workspace/:wid/element/:eid",
    "title": "Assembly Definition",
    "name": "GetAssemblyDefinition",
    "description": "<p>Get definition of requested assembly</p> ",
    "group": "Model",
    "version": "0.1.0",
    "permission": [
      {
        "name": "auth",
        "title": "Authenticated access only",
        "description": "<p>Must be logged in to access this resource.</p> "
      }
    ]
}
```

These are simple to get rid of on the front end that I'm feeding the JSON to, but I think it'd be best to not have them be there in the first place, to separate data from markup. Thoughts?

**Comment by tylucaskelley** [comment]
Closing and opening new issue in spec repo instead, more appropriate.

**Comment by MarkHerhold** [comment]
for reference, it was moved here: https://github.com/apidoc/apidoc-spec/issues/2
