### ISSUE TITLE
FR: OpenAPI support?

### ISSUE THREAD

**Issue by viezel** [apidoc/apidoc-core#60]
It would be very beneficial if this lib would be able to generate OpenAPI spec document. (https://www.openapis.org/)

**Comment by viezel** [comment]
The detailed overview of version 2.0 is here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by shawninder** [comment]
@viezel Maybe this can get you started: https://github.com/brownstein/apidoc-swagger

The Swagger format is OpenAPI, so you can use this and not use [Swagger](https://swagger.io/) is you like...

**Comment by terrasoff** [comment]
@viezel i haven't tried it yet
but i think [this package](https://www.npmjs.com/package/@forfuture/apidoc-openapi) might help you

**Comment by NicolasCARPi** [comment]
Hello,

Given that a package exists already to do exactly that, I'm closing this issue.
