### ISSUE TITLE
Little improvement of @apiGroup request

### ISSUE THREAD

**Issue by gigacoderr** [apidoc/apidoc-core#74]
Hi!
During parsing @apiGroup, all non-latin symbols treating as 'special chars' and replacing with '_'. It is a bug, which obstacle.

Please, replace regular expression '/[^\w]/g' with '/[.*+?^${}()|[\]\\]/g' in 'apidoc-core/lib/workers/api_group.js' in function 'postProcess', line 83.

Big thanks, sorry for my English.

**Comment by NicolasCARPi** [comment]
This has been added and will be part of the next release.
