### ISSUE TITLE
Parser in the browser?

### ISSUE THREAD

**Issue by rolandpoulter** [apidoc/apidoc-core#8]
I'd like to be able to use apidoc parser in a browser, however I cannot because it requires the `fs` module.

It would be nice if the calls to `fs.readFileSync` could be refactored out of the parser? I want to use apidoc dynamically in the client for lazily generated documentation.

Is this feasible?

**Comment by rottmann** [comment]
Set it on todo, on an other issue was the request to set all command-line params and apidoc.json settings with a grunt-task, so your request fits to.

**Comment by MarkHerhold** [comment]
@rolandpoulter Browserify and others will stub in a substitute for the fs module when packaging. You should take a look at that.
