### ISSUE TITLE
Nullable param types using char "?"

### ISSUE THREAD

**Issue by gponcon** [apidoc/apidoc-core#82]
Give the possibility of specifying a nullable parameter with this notation, as with PHP 7.1 : 

```
@apiParam {?MyType} myParameter ...
```

Therefore replace the `type:` regex in `parsers/api_params.js` by : `'(\\?[a-zA-Z0-9\(\)#:\\.\\/\\\\\\[\\]_-]+)'` ?

**Comment by NicolasCARPi** [comment]
Hello,

I think it should start with `'(\\??` to make the `?` optional. Wouldn't you agree?
