### ISSUE TITLE
Error in the documentation about erlang parser

### ISSUE THREAD

**Issue by Xavier59** [apidoc/apidoc-core#90]
Hello,

The following file indicated that the delimiters for elixir files are `'''` : https://github.com/apidoc/apidoc-core/blob/2069f4e4495433b98c8d424092fa5ba629dc33b1/lib/languages/ex.js#L8

But on the http://apidocjs.com/ website, it seems to indicate that the delimiters are `#{`, `#` and `#}`

![image](https://user-images.githubusercontent.com/10245003/65042390-0a526700-d959-11e9-8edb-e4732873ca4f.png)

**Comment by NicolasCARPi** [comment]
Fixed in https://github.com/apidoc/apidoc-core/pull/65
